version: '3.9'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=567234
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        ports:
           - 8000:8000
        command: bash -c 
            "alembic upgrade head 
            && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        depends_on:
            - db

volumes:
  postgres_data: